version: '3'

networks:
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local

services:
  api:
    build:
      context: ./
    volumes:
      - ../:/var/www/html/
    ports:
      - "${API_PORT}:80"
    working_dir: /var/www/html/
    networks:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - TZ=UTC
    volumes:
      - ${VOLUME_DATA}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
